const path = require('path');

const baseCSSLoaders = require('./baseCSSLoaders');

module.exports = {
  test: /\.module\.scss$/,
  use: [
    {
      loader: path.resolve(__dirname, '..', '..', 'webpack', 'loaders', 'type-declarations-for-css-modules.js'),
      options: {
        banner: '// This file is automatically generated by typings-for-css-modules.\n// Please do not change this file!'
      }
    },
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: '[local]__[hash:base64:5]',
          mode: 'local',
        },
        importLoaders: 2,
        localsConvention: 'camelCaseOnly',
      }
    },
    ...baseCSSLoaders
  ]
};
